# Generated by Django 2.2.1 on 2019-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="club")),
                ("mail", models.EmailField(max_length=254)),
                ("website", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("picture", models.ImageField(upload_to="event")),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date", models.DateField()),
                ("picture", models.ImageField(upload_to="news")),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("logo", models.ImageField(upload_to="partner")),
                ("mail", models.EmailField(max_length=254)),
                ("website", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("picture", models.ImageField(upload_to="team_member")),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("Président", "Président"),
                            ("Présidente", "Présidente"),
                            ("Vice-Président", "Vice-Président"),
                            ("Vice-Présidente", "Vice-Présidente"),
                            ("Trésorier", "Trésorier"),
                            ("Trésorière", "Trésorière"),
                            ("Vice-Trésorier", "Vice-Trésorier"),
                            ("Vice-Trésorière", "Vice-Trésorière"),
                            ("Secrétaire", "Secrétaire"),
                            ("Vice-Secrétaire", "Vice-Secrétaire"),
                            ("Communication", "Communication"),
                            ("Partenariats", "Partenariats"),
                            ("Responsable Technique", "Responsable Technique"),
                            ("Président du Foyer", "Président du Foyer"),
                            ("Autre", "Autre"),
                        ],
                        max_length=200,
                    ),
                ),
                ("mail", models.EmailField(max_length=254)),
            ],
        ),
    ]
