# Generated by Django 3.0.4 on 2020-04-04 19:55

import ckeditor.fields
from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('logo', stdimage.models.StdImageField(upload_to='club', validators=[stdimage.validators.MinSizeValidator(360, 360)])),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('picture', stdimage.models.StdImageField(upload_to='event', validators=[stdimage.validators.MinSizeValidator(800, 600)])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalWebsiteParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontpage_video', models.FileField(default=None, upload_to='global_parameters')),
                ('default_adhesion_picture', stdimage.models.StdImageField(default=None, upload_to='global_parameters', validators=[stdimage.validators.MinSizeValidator(230, 292), stdimage.validators.MaxSizeValidator(1080, 720)])),
                ('conditions_adhesion', models.FileField(default=None, upload_to='global_parameters')),
                ('insa_description', ckeditor.fields.RichTextField()),
                ('aeir_description', ckeditor.fields.RichTextField()),
                ('adhesion_description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('picture', stdimage.models.StdImageField(upload_to='news', validators=[stdimage.validators.MinSizeValidator(800, 600)])),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('logo', stdimage.models.StdImageField(upload_to='partner', validators=[stdimage.validators.MinSizeValidator(800, 100)])),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('picture', stdimage.models.StdImageField(default=None, upload_to='team_member', validators=[stdimage.validators.MinSizeValidator(230, 300)])),
                ('post', models.CharField(choices=[('Président', 'Président'), ('Présidente', 'Présidente'), ('Vice-Président', 'Vice-Président'), ('Vice-Présidente', 'Vice-Présidente'), ('Trésorier', 'Trésorier'), ('Trésorière', 'Trésorière'), ('Vice-Trésorier', 'Vice-Trésorier'), ('Vice-Trésorière', 'Vice-Trésorière'), ('Secrétaire', 'Secrétaire'), ('Vice-Secrétaire', 'Vice-Secrétaire'), ('Communication', 'Communication'), ('Partenariats', 'Partenariats'), ('Responsable Technique', 'Responsable Technique'), ('Président du Foyer', 'Président du Foyer'), ('Autre', 'Autre')], max_length=200)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
