# Generated by Django 2.2.1 on 2019-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_auto_20191025_1403"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
