# Generated by Django 2.2.1 on 2019-12-25 10:54

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=stdimage.models.StdImageField(
                upload_to="club",
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=stdimage.models.StdImageField(
                upload_to="event",
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="picture",
            field=stdimage.models.StdImageField(
                upload_to="news",
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=stdimage.models.StdImageField(
                upload_to="partner",
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="picture",
            field=stdimage.models.StdImageField(
                upload_to="team_member",
                validators=[stdimage.validators.MinSizeValidator(800, 600)],
            ),
        ),
    ]
