# Generated by Django 3.0.1 on 2020-01-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_auto_20191225_1054"),
    ]

    operations = [
        migrations.DeleteModel(name="Question",),
    ]
