# Generated by Django 3.0.1 on 2020-01-05 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_delete_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="news", name="content", field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
