# Generated by Django 3.0.1 on 2020-01-05 19:57

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_auto_20200105_1628"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalWebsiteParameters",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frontpage_video", models.FileField(upload_to="global_parameters")),
                ("insa_description", ckeditor.fields.RichTextField()),
                ("aeir_description", ckeditor.fields.RichTextField()),
                ("adhesion_description", ckeditor.fields.RichTextField()),
                (
                    "adhesion_price",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("adhesion_ticketting_activated", models.BooleanField(default=False)),
                ("adhesion_ticketting_link", models.CharField(max_length=200)),
            ],
        ),
    ]
