# Generated by Django 3.0.1 on 2020-01-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_globalwebsiteparameters_default_adhesion_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalwebsiteparameters", name="adhesion_price",
        ),
        migrations.RemoveField(
            model_name="globalwebsiteparameters", name="adhesion_ticketting_activated",
        ),
        migrations.RemoveField(
            model_name="globalwebsiteparameters", name="adhesion_ticketting_link",
        ),
    ]
