# Generated by Django 3.0.1 on 2020-01-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_auto_20200106_1217"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalwebsiteparameters",
            name="sell_conditions",
            field=models.FileField(default=None, upload_to="global_parameters"),
            preserve_default=False,
        ),
    ]
