# Generated by Django 3.0.1 on 2020-01-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_remove_globalwebsiteparameters_sell_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalwebsiteparameters",
            name="conditions_adhesion",
            field=models.FileField(default=None, upload_to="global_parameters"),
        ),
        migrations.AlterField(
            model_name="globalwebsiteparameters",
            name="frontpage_video",
            field=models.FileField(default=None, upload_to="global_parameters"),
        ),
    ]
