# Generated by Django 3.0.1 on 2020-01-08 12:16

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_auto_20200107_1745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="picture",
            field=stdimage.models.StdImageField(
                default=None,
                upload_to="team_member",
                validators=[stdimage.validators.MinSizeValidator(230, 300)],
            ),
        ),
    ]
