# Generated by Django 3.0.1 on 2020-01-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_auto_20200108_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="mail",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="partner",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
