# Generated by Django 3.0.1 on 2020-01-08 12:36

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_auto_20200108_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=stdimage.models.StdImageField(
                upload_to="partner",
                validators=[stdimage.validators.MinSizeValidator(800, 100)],
            ),
        ),
    ]
