# Generated by Django 3.0.1 on 2020-01-12 14:56

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_auto_20200108_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=stdimage.models.StdImageField(
                upload_to="club",
                validators=[stdimage.validators.MinSizeValidator(360, 360)],
            ),
        ),
    ]
