# Generated by Django 3.0.4 on 2020-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adhesion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('participants_non_adherents', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(blank=True, default=800)),
                ('participants', models.ManyToManyField(blank=True, default=0, to='adhesion.Adhesion')),
            ],
        ),
    ]
