# Generated by Django 2.2.1 on 2019-12-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanagement",
            name="max_capacity",
            field=models.IntegerField(blank=True),
        ),
    ]
