# Generated by Django 2.2.1 on 2019-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_auto_20191201_1321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanagement",
            name="participants",
            field=models.ManyToManyField(blank=True, to="adhesion.Adhesion"),
        ),
    ]
