# Generated by Django 2.2.1 on 2019-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_auto_20191201_1322"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanagement",
            name="participants",
            field=models.ManyToManyField(to="adhesion.Adhesion"),
        ),
    ]
