# Generated by Django 2.2.1 on 2019-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_auto_20191201_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanagement",
            name="max_capacity",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
