# Generated by Django 2.2.1 on 2019-12-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_auto_20191201_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventmanagement",
            name="max_capacity",
            field=models.IntegerField(blank=True, default=800),
        ),
    ]
