# Generated by Django 2.2.1 on 2019-09-25 19:20

import adhesion.models
import datetime
from django.db import migrations, models
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhesion_type', models.CharField(choices=[('Adhésion AEIR', 'Adhésion AEIR'), ('Adhésion Foyer', 'Adhésion Foyer')], max_length=15)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('email', models.EmailField(max_length=254)),
                ('picture', stdimage.models.StdImageField(upload_to='adhesion_AEIR', validators=[stdimage.validators.MaxSizeValidator(1080, 720)])),
                ('insa_student', models.BooleanField()),
                ('school_year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Autre', 'Autre')], max_length=200)),
                ('departement', models.CharField(choices=[('STPI', 'STPI'), ('GM', 'GM'), ('INFO', 'INFO'), ('SRC', 'SRC'), ('EII', 'EII'), ('GMA', 'GMA'), ('SGM', 'SGM'), ('GCU', 'GCU'), ('CDTI', 'CDTI'), ('Autre', 'Autre')], max_length=200)),
                ('adhesion_date', models.DateField(auto_now_add=True)),
                ('card_id', models.CharField(default=adhesion.models.random_id, max_length=8)),
                ('card_pwd', models.CharField(default=adhesion.models.random_id, max_length=8)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedAdhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhesion_type', models.CharField(choices=[('Adhésion AEIR', 'Adhésion AEIR'), ('Adhésion Foyer', 'Adhésion Foyer')], max_length=15)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('insa_student', models.BooleanField()),
                ('school_year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('Autre', 'Autre')], max_length=200)),
                ('departement', models.CharField(choices=[('STPI', 'STPI'), ('GM', 'GM'), ('INFO', 'INFO'), ('SRC', 'SRC'), ('EII', 'EII'), ('GMA', 'GMA'), ('SGM', 'SGM'), ('GCU', 'GCU'), ('CDTI', 'CDTI'), ('Autre', 'Autre')], max_length=200)),
                ('adhesion_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
