# Generated by Django 2.2.1 on 2019-10-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0002_auto_20190930_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='picture',
            field=models.ImageField(upload_to='adhesion_AEIR'),
        ),
    ]
