# Generated by Django 2.2.1 on 2019-11-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0003_auto_20191003_1151"),
    ]

    operations = [
        migrations.AddField(
            model_name="adhesion",
            name="valid_infos",
            field=models.BooleanField(default=False),
        ),
    ]
