# Generated by Django 2.2.1 on 2019-11-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0004_adhesion_valid_infos"),
    ]

    operations = [
        migrations.RemoveField(model_name="adhesion", name="adhesion_type",),
        migrations.RemoveField(model_name="archivedadhesion", name="adhesion_type",),
        migrations.AlterField(
            model_name="adhesion",
            name="valid_infos",
            field=models.BooleanField(default=True),
        ),
    ]
