# Generated by Django 2.2.1 on 2019-12-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0005_auto_20191112_1021"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedadhesion",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="archivedadhesion",
            name="adhesion_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="archivedadhesion",
            name="departement",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="archivedadhesion",
            name="school_year",
            field=models.CharField(max_length=200),
        ),
    ]
