# Generated by Django 3.0.1 on 2020-01-05 16:01

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ("adhesion", "0007_auto_20191225_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adhesion",
            name="picture",
            field=stdimage.models.StdImageField(
                upload_to="adhesion_aeir",
                validators=[
                    stdimage.validators.MinSizeValidator(230, 292),
                    stdimage.validators.MaxSizeValidator(1080, 720),
                ],
            ),
        ),
    ]
