# Generated by Django 3.0.1 on 2020-01-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0009_auto_20200113_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='picture',
        ),
    ]
