# Generated by Django 3.0.1 on 2020-01-25 20:01

from django.db import migrations
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0010_remove_adhesion_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='picture',
            field=stdimage.models.StdImageField(default=None, upload_to='adhesion_aeir', validators=[stdimage.validators.MinSizeValidator(230, 292), stdimage.validators.MaxSizeValidator(1080, 720)]),
            preserve_default=False,
        ),
    ]
