# Generated by Django 3.0.1 on 2020-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0011_adhesion_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='insa_student',
            field=models.BooleanField(choices=[('Oui', True), ('Non', False)], default=False),
        ),
    ]
