# Generated by Django 3.0.1 on 2020-03-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0012_auto_20200130_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedadhesion',
            name='adhesion_date',
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='insa_student',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=False),
        ),
    ]
