# Generated by Django 3.0.1 on 2020-03-21 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adhesion', '0013_auto_20200302_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
